export const WILAYAH_INDONESIA = {
  "Aceh": ["Banda Aceh", "Langsa", "Lhokseumawe", "Meulaboh", "Sabang"],
  "Bali": ["Badung", "Buleleng", "Denpasar", "Gianyar", "Karangasem"],
  "Bangka Belitung": ["Pangkalpinang", "Tanjung Pandan"],
  "Banten": ["Cilegon", "Serang", "Tangerang", "Tangerang Selatan"],
  "Bengkulu": ["Bengkulu"],
  "DI Yogyakarta": ["Bantul", "Gunungkidul", "Kulon Progo", "Sleman", "Yogyakarta"],
  "DKI Jakarta": ["Jakarta Barat", "Jakarta Pusat", "Jakarta Selatan", "Jakarta Timur", "Jakarta Utara", "Kepulauan Seribu"],
  "Gorontalo": ["Gorontalo"],
  "Jambi": ["Jambi", "Sungai Penuh"],
  "Jawa Barat": ["Bandung", "Banjar", "Bekasi", "Bogor", "Cimahi", "Cirebon", "Depok", "Sukabumi", "Tasikmalaya"],
  "Jawa Tengah": ["Cilacap", "Magelang", "Pekalongan", "Salatiga", "Semarang", "Surakarta", "Tegal"],
  "Jawa Timur": ["Batu", "Blitar", "Banyuwangi", "Kediri", "Madiun", "Mojokerto", "Malang", "Pasuruan", "Probolinggo", "Surabaya"],
  "Kalimantan Barat": ["Pontianak", "Singkawang"],
  "Kalimantan Selatan": ["Banjarbaru", "Banjarmasin"],
  "Kalimantan Tengah": ["Palangkaraya"],
  "Kalimantan Timur": ["Balikpapan", "Bontang", "Samarinda"],
  "Kalimantan Utara": ["Tanjung Selor", "Tarakan"],
  "Kepulauan Riau": ["Batam", "Bintan", "Karimun", "Natuna", "Tanjungpinang"],
  "Lampung": ["Bandar Lampung", "Metro"],
  "Maluku": ["Ambon", "Tual"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan"],
  "Nusa Tenggara Barat": ["Bima", "Mataram"],
  "Nusa Tenggara Timur": ["Kupang", "Labuan Bajo", "Maumere"],
  "Papua": ["Jayapura"],
  "Papua Barat": ["Manokwari", "Sorong"],
  "Riau": ["Dumai", "Pekanbaru"],
  "Sulawesi Barat": ["Mamuju"],
  "Sulawesi Selatan": ["Bone", "Bulukumba", "Makassar", "Palopo", "Parepare"],
  "Sulawesi Tengah": ["Luwuk", "Palu"],
  "Sulawesi Tenggara": ["Baubau", "Kendari"],
  "Sulawesi Utara": ["Bitung", "Kotamobagu", "Manado", "Tomohon"],
  "Sumatera Barat": ["Bukittinggi", "Padang", "Pariaman", "Payakumbuh", "Sawahlunto", "Solok"],
  "Sumatera Selatan": ["Lubuklinggau", "Pagar Alam", "Palembang", "Prabumulih"],
  "Sumatera Utara": ["Binjai", "Medan", "Pematangsiantar", "Sibolga", "Tanjungbalai", "Tebing Tinggi"]
} as const;
