#!/usr/bin/env python3
"""Generate a compact land bitmap for the Indonesia region.

Downloads Natural Earth 110m land GeoJSON, rasterizes it into a 0.1-degree
grid (lat -11..6, lon 95..141), and writes components/peta-risiko/landGrid.ts
so the client can compute distance from any point to the nearest coast.

Usage:
    python3 scripts/generate-land-grid.py
"""
import base64
import json
import urllib.request

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
FALLBACK_URL = "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json"

MIN_LAT, MAX_LAT = -11.0, 6.0
MIN_LON, MAX_LON = 95.0, 141.0
STEP = 0.1
ROWS = int((MAX_LAT - MIN_LAT) / STEP)   # 170
COLS = int((MAX_LON - MIN_LON) / STEP)   # 460

OUT = "components/peta-risiko/landGrid.ts"


def fetch_geojson() -> dict:
    local = ["/tmp/ne_110m_land.geojson", "scripts/ne_110m_land.geojson"]
    for path in local:
        try:
            with open(path) as f:
                return json.load(f)
        except FileNotFoundError:
            pass
    # macOS Python often lacks the system CA bundle → use curl
    import subprocess
    for url in (URL, FALLBACK_URL):
        try:
            out = subprocess.run(
                ["curl", "-sL", "-m", "60", url], capture_output=True, check=True, text=True
            )
            return json.loads(out.stdout)
        except Exception as exc:
            print(f"  fetch failed ({url}): {exc}")
    raise SystemExit("No land dataset available")


def point_in_polygon(lon: float, lat: float, rings: list) -> bool:
    """Ray-casting point-in-polygon test (works for any ring orientation)."""
    inside = False
    for ring in rings:
        n = len(ring)
        j = n - 1
        for i in range(n):
            xi, yi = ring[i]
            xj, yj = ring[j]
            if (yi > lat) != (yj > lat) and lon < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
    return inside


def main() -> None:
    print("Downloading Natural Earth land data…")
    data = fetch_geojson()

    polys = []
    for feat in data["features"]:
        geom = feat.get("geometry") or {}
        if geom.get("type") == "Polygon":
            polys.append(geom["coordinates"])
        elif geom.get("type") == "MultiPolygon":
            polys.extend(geom["coordinates"])

    # Bbox pre-filter to skip polygons far from Indonesia
    filt = []
    for rings in polys:
        flat = [pt for ring in rings for pt in ring]
        lons = [p[0] for p in flat]
        lats = [p[1] for p in flat]
        if min(lons) <= MAX_LON and max(lons) >= MIN_LON and min(lats) <= MAX_LAT and max(lats) >= MIN_LAT:
            filt.append(rings)
    print(f"Polygons in region: {len(filt)}/{len(polys)}")

    bits = []
    for r in range(ROWS):
        lat = MAX_LAT - (r + 0.5) * STEP
        for c in range(COLS):
            lon = MIN_LON + (c + 0.5) * STEP
            land = any(point_in_polygon(lon, lat, rings) for rings in filt)
            bits.append("1" if land else "0")
    bitstring = "".join(bits)

    packed = bytearray()
    for i in range(0, len(bitstring), 8):
        packed.append(int(bitstring[i:i + 8].ljust(8, "0"), 2))
    b64 = base64.b64encode(bytes(packed)).decode()

    land_cells = bits.count("1")
    print(f"Grid {ROWS}x{COLS}, land cells {land_cells} ({land_cells / len(bits) * 100:.1f}%)")

    ts = f"""// AUTO-GENERATED by scripts/generate-land-grid.py — do not edit manually.
// Land bitmap for Indonesia region (Natural Earth 110m), {STEP}-degree grid.
export const LAND_MIN_LAT = {MIN_LAT};
export const LAND_MAX_LAT = {MAX_LAT};
export const LAND_MIN_LON = {MIN_LON};
export const LAND_MAX_LON = {MAX_LON};
export const LAND_ROWS = {ROWS};
export const LAND_COLS = {COLS};
export const LAND_GRID_B64 = "{b64}";
"""
    with open(OUT, "w") as f:
        f.write(ts)
    print(f"Wrote {OUT} ({len(ts)} bytes)")


if __name__ == "__main__":
    main()
